### ISSUE TITLE
G++ Error in some windows systems

### ISSUE THREAD

**Issue by Abdelghafour01** [shikharkunal99/Sublime-Build-System#1]
Sometimes there is a massive error message displayed when trying to compile a C++ file.
You can see the full error here:
http://stackoverflow.com/questions/38538924/g-updated-on-mingw-gets-massive-error-messages

The solution is to change std=c++11 by std=gnu++11 in the compile command.

**Comment by shikharkunal99** [comment]
using std=gnu++11 will give no such file or directory error in some systems. 
The solution is to remove this.
Thanks for pointing it out.
