### ISSUE TITLE
/bin/sh: 1: cannot open inputf.in: No such file

### ISSUE THREAD

**Issue by snapfast** [shikharkunal99/Sublime-Build-System#3]
/bin/sh: 1: cannot open inputf.in: No such file

Not able to take input in c or cpp program.
I used Linux code for the data input. Not working.

my code below.

    #include <stdio.h>
    // #include <conio.h>
    int main(int argc, char const *argv[])
    {
	    int x = 99;
	    int y = 100;
	    //x = x * y / x = y;
	    scanf("%d", &x);
	    printf("%d %d\n", x, y );
	    return 0;
    }

**Comment by shikharkunal99** [comment]
See the error properly. You have not created the input file at the appropriate location.
