### ISSUE TITLE
Problem In taking input 

### ISSUE THREAD

**Issue by MotiBaadror** [shikharkunal99/Sublime-Build-System#4]
there is nothing as an output 
os: win 10;
sublime text 3;

#include <iostream>
#include <bits/stdc++.h>
using namespace std;

int main()
{
	int n;
cin>>n;
while(n--)
{
int a;
cin>>a;
cout<<a<<endl;
	
	return 0;

}
input.in
4
1
2
3
4

**Comment by shikharkunal99** [comment]
C:\Users\Moti Baadror\Desktop\youtube\input.in: file not recognized: File truncated

Looks like you are trying to run inputf.in file instead of .cpp file.
